server:
  port: 9090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://150.28.66.46:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true
    
security:
  sessions: NEVER
  oauth2:
    resource:
      userInfoUri: http://150.28.66.46:9999/uaa/user
      jwt:
        keyValue : 
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAowHcWrnVKh/DPjwI7awu
          fCc2BrH7IBcu4IQewKX64lXXyHOHBzj9/vQGy6+YM6Wy1rzTfymz55EwzB7+z7uX
          WBjZvMDgmwc8+SoCKd5qKfhXFPu3sbES0xmYEDO18xNrtv2It+K1A6gPQG2YjfrL
          vRk3RDzM2YvUI+BSCefXNJX1pw+OLoJ99Bbp7J4sE3mj2rT0OkW++xLf4ZZ3MKxZ
          PIdD/71ASotFgIxu7l5b/Kau/6z3yugn7bHwHecHBI68yiB7+z1/da6Xhx6qg8YM
          qpk4luX9Sfz1OvrltTFFtDOL5jAHPOnV1OcsIHmBL6tVyP5qXBJgU4myG34nOGf9
          ewIDAQAB
          -----END PUBLIC KEY-----