server:
  port: 8080
  tomcat:
    protocol-header: x-forwarded-proto
#    protocol-header-https-value: https
    remote-ip-header: x-forwarded-for
  use:
    forward-headers : true
    
    
       

info:
  component: Edge Server

eureka:
  instance:
    hostname: edge
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://150.28.66.46:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  user:
     password: password
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      access-token-uri: http://150.28.66.46:9999/uaa/oauth/token
      user-authorization-uri: http://150.28.66.46:9999/uaa/oauth/authorize
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAowHcWrnVKh/DPjwI7awu
          fCc2BrH7IBcu4IQewKX64lXXyHOHBzj9/vQGy6+YM6Wy1rzTfymz55EwzB7+z7uX
          WBjZvMDgmwc8+SoCKd5qKfhXFPu3sbES0xmYEDO18xNrtv2It+K1A6gPQG2YjfrL
          vRk3RDzM2YvUI+BSCefXNJX1pw+OLoJ99Bbp7J4sE3mj2rT0OkW++xLf4ZZ3MKxZ
          PIdD/71ASotFgIxu7l5b/Kau/6z3yugn7bHwHecHBI68yiB7+z1/da6Xhx6qg8YM
          qpk4luX9Sfz1OvrltTFFtDOL5jAHPOnV1OcsIHmBL6tVyP5qXBJgU4myG34nOGf9
          ewIDAQAB
          -----END PUBLIC KEY-----
    authorization:
      check-token-access: isAuthenticated() 

zuul:
  ignoredServices: "*"
  routes:
    product-service: 
      path: /product/**
    point-service:
      path: /point/**
    composite-service:
      path:  /composite/**
    service-container:
      path: /service/**
    user:
      path: /user/**
      url: http://150.28.66.46:9999/uaa/user
#    edge :
#      path: /resource/**
#      url: http://localhost:9000

#logging:
#  level: 
#    ROOT : DEBUG
    