server:
  port: 8765

info:
  component: Edge Server

eureka:
  instance:
    hostname: edge
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  oauth2:
    resource:
      userInfoUri: https://localhost:9999/oauth/user
      
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    product-service: 
      path: /product/**
    point-service: 
      path: /point/**
    composite-service:
      path:  /composite/**