server:
  port: 8765

info:
  component: Edge Server

eureka:
  instance:
    hostname: edge
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    composite-service: /product/**
    POINT-SERVICE: /point/**