server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://150.28.66.46:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/beatificx/microservice-config